#%RAML 1.0
title: Example API
protocols: HTTPS
version: v1
baseUri: https://example.com/api/{version}
mediaType: application/json

types:
  Error:
    properties:
      code: integer
      message: string
  Gender:
    type: string
    enum: [ male, female ]
  UserBase:
    properties:
      name: string
      gender?: Gender
  User:
    properties:
      id: integer
      name: string
      gender?: Gender
    example:
      {
        "id": 42,
        "name": "John Doe",
        "gender": "male"
      }
  Users: User[]

/users:
  get:
    description: Get all users.
    responses:
      200:
        body:
          type: Users
  post:
    description: Create new Kicker player.
    body:
      type: UserBase
    responses:
      201:
        description: New user created successful.
      400:
        description: Required properties missing or validation issues.
        body:
          type: Error
