#%RAML 1.0
title: Example API
protocols: HTTPS
version: v1
baseUri: https://example.com/api/{version}
mediaType: application/json

types:
  Gender:
    type: string
    enum: [ male, female ]
  User:
    properties:
      id: integer
      name: string
      gender?: Gender
    example:
      {
        "id": 42,
        "name": "John Doe",
        "gender": "male"
      }
  Users: User[]

/users:
  get:
    description: Get all users.
    responses:
      200:
        body:
          type: Users
